name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: r507_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup test database
        run: |
          cp .env.test .env.test.local
          echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/r507_test?serverVersion=8.0" > .env.test.local
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --env=test --no-interaction
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Run tests
        run: php bin/phpunit

  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --no-scripts
        env:
          APP_ENV: prod

      - name: Create production .env.local
        run: |
          echo "APP_ENV=prod" > .env.local
          echo "APP_DEBUG=0" >> .env.local

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 51.38.224.153
          username: basile
          password: '&167tZkx0'
          port: 21
          protocol: ftp
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**/.git
            **/tests/**
            **/src/DataFixtures/**
            var/cache/**
            var/log/**
            .env.local
            .env.*.local

